/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedBriefRouteImport } from './routes/_authenticated/brief'
import { Route as AuthenticatedBriefingPreferencesRouteImport } from './routes/_authenticated/briefing-preferences'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedRosyBotRouteImport } from './routes/_authenticated/rosy-bot'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRestaurantsIndexRouteImport } from './routes/_authenticated/restaurants.index'
import { Route as AuthenticatedRestaurantsLocationIdRouteImport } from './routes/_authenticated/restaurants.$locationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefRoute = AuthenticatedBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingPreferencesRoute =
  AuthenticatedBriefingPreferencesRouteImport.update({
    id: '/briefing-preferences',
    path: '/briefing-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosyBotRoute = AuthenticatedRosyBotRouteImport.update({
  id: '/rosy-bot',
  path: '/rosy-bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestaurantsIndexRoute =
  AuthenticatedRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRestaurantsLocationIdRoute =
  AuthenticatedRestaurantsLocationIdRouteImport.update({
    id: '/restaurants/$locationId',
    path: '/restaurants/$locationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/brief': typeof AuthenticatedBriefRoute
  '/briefing-preferences': typeof AuthenticatedBriefingPreferencesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/rosy-bot': typeof AuthenticatedRosyBotRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/restaurants/$locationId': typeof AuthenticatedRestaurantsLocationIdRoute
  '/restaurants/': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/brief': typeof AuthenticatedBriefRoute
  '/briefing-preferences': typeof AuthenticatedBriefingPreferencesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/rosy-bot': typeof AuthenticatedRosyBotRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/restaurants/$locationId': typeof AuthenticatedRestaurantsLocationIdRoute
  '/restaurants': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/brief': typeof AuthenticatedBriefRoute
  '/_authenticated/briefing-preferences': typeof AuthenticatedBriefingPreferencesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/rosy-bot': typeof AuthenticatedRosyBotRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/restaurants/$locationId': typeof AuthenticatedRestaurantsLocationIdRoute
  '/_authenticated/restaurants/': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/actions'
    | '/alerts'
    | '/brief'
    | '/briefing-preferences'
    | '/finance'
    | '/guests'
    | '/integrations'
    | '/inventory'
    | '/investor'
    | '/marketing'
    | '/menu'
    | '/monitoring'
    | '/overview'
    | '/people'
    | '/rosy-bot'
    | '/sales'
    | '/settings'
    | '/restaurants/$locationId'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/actions'
    | '/alerts'
    | '/brief'
    | '/briefing-preferences'
    | '/finance'
    | '/guests'
    | '/integrations'
    | '/inventory'
    | '/investor'
    | '/marketing'
    | '/menu'
    | '/monitoring'
    | '/overview'
    | '/people'
    | '/rosy-bot'
    | '/sales'
    | '/settings'
    | '/restaurants/$locationId'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/actions'
    | '/_authenticated/alerts'
    | '/_authenticated/brief'
    | '/_authenticated/briefing-preferences'
    | '/_authenticated/finance'
    | '/_authenticated/guests'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/investor'
    | '/_authenticated/marketing'
    | '/_authenticated/menu'
    | '/_authenticated/monitoring'
    | '/_authenticated/overview'
    | '/_authenticated/people'
    | '/_authenticated/rosy-bot'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/restaurants/$locationId'
    | '/_authenticated/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brief': {
      id: '/_authenticated/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof AuthenticatedBriefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing-preferences': {
      id: '/_authenticated/briefing-preferences'
      path: '/briefing-preferences'
      fullPath: '/briefing-preferences'
      preLoaderRoute: typeof AuthenticatedBriefingPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rosy-bot': {
      id: '/_authenticated/rosy-bot'
      path: '/rosy-bot'
      fullPath: '/rosy-bot'
      preLoaderRoute: typeof AuthenticatedRosyBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurants/': {
      id: '/_authenticated/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof AuthenticatedRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurants/$locationId': {
      id: '/_authenticated/restaurants/$locationId'
      path: '/restaurants/$locationId'
      fullPath: '/restaurants/$locationId'
      preLoaderRoute: typeof AuthenticatedRestaurantsLocationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBriefRoute: typeof AuthenticatedBriefRoute
  AuthenticatedBriefingPreferencesRoute: typeof AuthenticatedBriefingPreferencesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedRosyBotRoute: typeof AuthenticatedRosyBotRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedRestaurantsLocationIdRoute: typeof AuthenticatedRestaurantsLocationIdRoute
  AuthenticatedRestaurantsIndexRoute: typeof AuthenticatedRestaurantsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBriefRoute: AuthenticatedBriefRoute,
  AuthenticatedBriefingPreferencesRoute: AuthenticatedBriefingPreferencesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedRosyBotRoute: AuthenticatedRosyBotRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedRestaurantsLocationIdRoute:
    AuthenticatedRestaurantsLocationIdRoute,
  AuthenticatedRestaurantsIndexRoute: AuthenticatedRestaurantsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
